f=open("file.txt","w")
f.write("Hello hexawarians....")

name=input("enter name: ")
age=input("Enter age: ")
salary=input("enter salary: ")
f.write(name)
f.write('\t')
f.write(age)
f.write('\t')
f.write(salary)
f.write('\t')

name=input("enter name: ")
age=input("Enter age: ")
salary=input("enter salary: ")

f.write(name)
f.write('\t')
f.write(age)
f.write('\t')
f.write(salary)
f.write('\t')
f.close()
